#!/bin/zsh

# Source checkers.sh
dotfiles_dir=$(dirname $(realpath ~/.zshrc))
source $dotfiles_dir/checkers.sh

# TODO make use of checkers?

# Syntax highlighting in `less`
# https://ole.michelsen.dk/blog/syntax-highlight-files-macos-terminal-less/
LESSPIPE=`which src-hilite-lesspipe.sh`
export LESSOPEN="| ${LESSPIPE} %s"
export LESS=' -R '

# Added these after running `brew install zsh-syntax-highlighting`
# https://github.com/zsh-users/zsh-syntax-highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters

# TODO this is technically available on other machines other than macOS, so
# this config doesn't strictly need to live here. Consider moving elsewhere.
# Added per install commands from https://github.com/nvbn/thefuck
eval "$(thefuck --alias)"

# Added per instruction after running `brew install chruby ruby-install`, which
# was run per instructions in https://jekyllrb.com/docs/installation/macos/
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
chruby ruby-3.1.2
# add brew-installed ruby to path
export PATH="/usr/local/opt/ruby/bin:$PATH"
# add gem (ruby) executable to path, per
# https://jekyllrb.com/docs/installation/macos/
export PATH="$PATH:$HOME/.gem/ruby/2.6.0/bin"

# Added after `brew install grep`
PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"

# Remove hints about Homebrew behaviour with environment variables (this is
# annoying to have around in `brew` command outputs). See: https://docs.brew.sh/Manpage
export HOMEBREW_NO_ENV_HINTS=1

# Setting env variable so that local formulae/cask changes (via `brew edit ...`)
# are not ignored. See: https://docs.brew.sh/FAQ#can-i-edit-formulae-myself
#
# Context here is that as of writing this, I've run `brew edit expressvpn` &
# added a `auto_updates true` line so that brew doesn't upgrade this cask —
# prefer not having this behavior for this particular cask because upgrade
# process is cumbersome & app seems to upgrade on its own.
export HOMEBREW_NO_INSTALL_FROM_API=1

# Per `brew install zsh-autosuggestions` instructions
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

## Following lines added by gcloud install script: https://cloud.google.com/sdk/docs/install#mac
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/izzyg/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/izzyg/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/izzyg/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/izzyg/google-cloud-sdk/completion.zsh.inc'; fi
