#!/bin/zsh

# Source checkers.sh
dotfiles_dir=$(dirname $(dirname $(realpath ~/.zprofile)))
source $dotfiles_dir/zsh/checkers.sh

if is_mac_os; then
    # Set up Homebrew, if installed; check Apple Silicon path first
    # (/opt/homebrew), then the Intel path (/usr/local).
    if [[ -x /opt/homebrew/bin/brew ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x /usr/local/bin/brew ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    else
        echo "~/.zprofile: Homebrew is not installed, please install by visiting https://brew.sh/."
        export HOMEBREW_NOT_INSTALLED=1
    fi
fi
